headerNames = ['N°','Immagine','Nome','Tipo','Abilità','Mosse Uovo','Costo',
               'Tot','PS','Att','Dif','ASp','DSp','Vel']
altText = ['Mosse','Principale','Speciale','Passiva','Cerca','Pot','Prec','PP',
           'Aggiungi ai filtri','Memoria','Crom.','Mossa Uovo','Mossa Uovo Rara',
           'Comuni','Mega','Ultra','MT','L.','Evo','Uova']
catToName = ['Tipo','Abilità','Mossa','Gen','Costo','Uova','Modalità',
             'Evoluzione','Forma','Bioma','Relativo a','Varianti Cromatiche','Etichetta']
infoText = [
    'Amicizia per Caramella', 'Passiva', 'Riduzione di Costo', 'Costi di un Uovo', 'Abilità Speciale', 
    'Solo da Uovo', 'Solo Baby', 'Pokémon Paradosso', 'Cambio Forma', 'Biomi', 'Filtri',
    'Ridotto dopo ## uova','per Livello','da Uovo','per MT'
]
biomeText = ['Comune','Non Comune','Raro','Super Raro','Ultra Raro',
             'Boss','Com.','NC','Raro','SR','UR','Alba','Giorno','Tramonto','Notte']
biomeLongText = [
    '<b>Questa forma è disponibile solo tramite <span style="color:rgb(140, 130, 240);">Cambio di Forma</span>.</b> Altre forme possono essere incontrate nel bioma mostrato.<br>',
    '<b>Questo Pokémon è <span style="color:rgb(143, 214, 154);">Esclusivo da Uovo</span>.</b><br>Non appare in alcun bioma, e può essere ottenuto solo dalle Uova.',
    '<b>Questo è un <span style="color:rgb(216, 143, 205);">Pokémon Baby</span>.</b><br>Non appare in alcun bioma, ma può essere ottenuto incontrando la sua evoluzione.',
    '<b>Questo <span style="color:rgb(239, 131, 131);">Pokémon Paradosso</span> è <span style="color:rgb(143, 214, 154);">Esclusivo da Uovo</span>.</b><br>Può essere ottenuto solo dalle Uova, ma in seguito può essere catturato nella modalità Classica.',
    'Questo Pokémon può essere catturato dopo aver ottenuto <b><span style="color:rgb(239, 131, 131);">Tutti gli Altri Pokémon</span></b>.<br>Non appare nelle Uova normali.',
    '<b>Questa forma non può essere ottenuta.</b>',
]
phrases = {
    'exclusive': 'Esclusivo',
    'new': 'Nuovo',
    'tag': 'Attributo',
    'theEnd': 'La Fine',
    'fullyEvolved': 'Completamente evoluto',
    'formBase': 'Base',
    'formMega': 'Mega',
    'formNewMega': 'Nuovo Mega',
    'formGiga': 'Gigamax',
    'formTransformed': 'Trasformato',
    'lureAbility': 'Abilità Esca',
    'ignoresAbilities': 'Ignora Abilità',
    'electricImmunity': 'Immunità Elettro',
    'fireImmunity': 'Immunità Fuoco',
    'waterImmunity': 'Immunità Acqua',
    'rainAbility': 'Abilità Pioggia',
    'sandAbility': 'Abilità Tempesta di Sabbia',
    'snowAbility': 'Abilità Neve',
    'sunAbility': 'Abilità Sole',
    'targetSwitchesOut': 'Forza il Cambio',
    'spreadMoves': 'Mosse ad Area',
}
substitutions = [
    ['Maschera ',''],
    ['Teracristal Ogerpon','Tera Ogerpon'],
]
warningText = [
    'Limitato ai Pokémon che hanno varianti cromatiche.',
    'Abilità limitate alle sole Abilità Principali.',
    'Abilità limitate alle sole Abilità Speciali.',
    'Abilità limitate alle sole Abilità Passive.',
    '<b>Non ci sono Pokémon che corrispondono ai filtri della ricerca.</b><br>Aggiungere un altro filtro potrebbe variare i risultati.',
    '<b>Clicca su un suggerimento per filtrarlo.</b><br>L’anteprima del filtro è solo per Nome/Tipo/Abilità.',
    '<b>Non ci sono Pokémon che corrispondono ai filtri della ricerca.</b><br>Prova una combinazione diversa.',
    '<b>Non ci sono Pokémon che corrispondono ai filtri.</b><br>Rimuovi i filtri o cambia le combinazioni di "O".',
    '<b>Non ci sono Pokémon che corrispondono ai filtri della ricerca.</b><br>Per favore, controlla l’ortografia e prova di nuovo.',
    'Clicca per visualizzare le istruzioni.',
]
procToDesc = [
    "Attacco Utilizzatore",
    "Difesa Utilizzatore",
    "Att. Sp. Utilizzatore",
    "Dif. Sp. Utilizzatore",
    "Velocità Utilizzatore",
    "Precisione Utilizzatore",
    "Elusione Utilizzatore",
    "Attacco",
    "Difesa",
    "Att. Sp.",
    "Dif. Sp.",
    "Velocità",
    "Precisione",
    "Elusione",
    "Avvelenamento",
    "Iperavvelenamento",
    "Sonno",
    "Congelamento",
    "Paralisi",
    "Scottatura",
    "Confusione",
    "Tentennamento",
    "Att/Dif/AttSp/DifSp/Vel Utilizzatore",
    "Avvelenamento/Paralisi/Sonno",
    "Scottatura/Paralisi/Congelamento",
    "Att/AttSp Utilizzatore Astrale",
    "Danno",
    "Priorità"
]
tagToDesc = [
    "Bersagli: Nemico Casuale",
    "Bersagli: Tutti i Nemici",
    "Bersagli: Intero Campo",
    "Alta Probabilità di Brutto Colpo",
    "Brutto Colpo Garantito",
    "Tasso di Brutto Colpo Utilizzatore +2",
    "Attacco Utilizzatore al massimo",
    "Consuma il 33% dei PS",
    "Consuma il 50% dei PS",
    "Contraccolpo del 50% dei PS",
    "Contraccolpo del 50% del danno",
    "Contraccolpo del 33% del danno",
    "Contraccolpo del 25% del danno",
    "30% infligge danno doppio",
    "Non utilizzato",
    "Cura il 100% del danno inflitto",
    "Cura il 75% del danno inflitto",
    "Cura il 50% del danno inflitto",
    "Cura in base all'Attacco del bersaglio",
    "Cura i Problemi di Stato",
    "Cura il Sonno",
    "Cura il Congelamento",
    "Cura la Scottatura",
    "Nessun effetto su Erba/Copricapo",
    "Nessun parassiseme su Pokémon Erba",
    "Attiva l'abilità Primacura",
    "Attiva l'abilità Sincrodanza",
    "Attiva l'abilità Vento Propizio",
    "Potenza aumentata da Affilama",
    "Potenza aumentata da Ferropugno",
    "Potenza aumentata da Megalancio",
    "Potenza aumentata da Ferromascella",
    "Potenza aumentata da Temerarietà",
    "Nessun effetto su Antiproiettile",
    "Impedita dall'abilità Umidità",
    "Mossa basata sul suono",
    "Ignora Sostituto",
    "Ignora Abilità",
    "Ignora Protezione",
    "L'Utilizzatore viene sostituito",
    "Il bersaglio viene sostituito",
    "Colpisce 2 volte",
    "Colpisce 3 volte",
    "Colpisce 10 volte",
    "Colpisce da 2 a 5 volte",
    "Si ripete per 2-3 turni",
    "Rimuove gli ostacoli",
    "Intrappola e danneggia il bersaglio",
    "Non può essere annullato",
    "Non può essere sostituito",
    "Non può essere ignorato",
    "Non può essere deviato",
    "Non può essere riflesso",
    "Colpisce sempre durante la pioggia",
    "L'Utilizzatore non può essere sostituito",
    "Il bersaglio non può essere sostituito",
    "Mossa da KO in un colpo",
    "Effetto modificato contro i Boss",
    "Nessun effetto contro i Boss",
    "Abilità Esca",
    "Mossa da Contatto",
    "Parzialmente Implementata",
    "Non Implementata",
]
helpMenuText = [
'Un <span style="color:rgb(140, 130, 240);">potente strumento di ricerca</span> per PokéRogue',
'Usa la <span style="color:rgb(140, 130, 240);">Barra di Ricerca</span> per aggiungere filtri:',
'Combina diversi filtri per ottenere ciò che vuoi',
'Clicca tra i filtri per usare la condizione "OR"',
'Clicca le <span style="color:rgb(140, 130, 240);">Intestazioni</span> per ordinare i risultati:',
'Clicca su <b>${headerNames[1]}</b> per vedere le varianti cromatiche',
'Clicca su <b>${headerNames[4]}</b> per restringere solo a un tipo:',
'Abilità Principali', '${infoText[4]}', '${infoText[1]}',
'<b>${headerNames[5]}</b> sono mostrate come <b>${fidToName[fidThreshold[4]]}</b> e <span style="color:rgb(240, 230, 140); font-weight: bold;">${fidToName[fidThreshold[4]+1]}</span>',
'Clicca l’intestazione per passare ai <b>${infoText[9]}</b>',
'Questa colonna mostrerà anche <b>filtrati ${altText[0]}/${infoText[9]}</b>',
'<b>${catToName[4]}</b> indica la rarità delle <b>${catToName[5]}</b>:',
'Clicca su una voce per vedere i dettagli di:',
'Clicca su un <b>${headerNames[2]}</b> per vedere tutte le mosse.',
'Il colore di <b>Pot</b> indica <span style="color:${col.or}; font-weight: bold;">Fisico</span> o <span style="color:${col.bl}; font-weight: bold;">Speciale</span> danno',
'Il colore di <b>Prec</b> indica <span style="color:${col.re}; font-weight: bold;">le Mosse Multicolpo</span>',
'Questo sito è stato creato da Sandstorm e tradotto in italiano con un po’ di aiuto. Non memorizzo cookie né raccolgo dati personali. Le immagini e i dati di gioco provengono dal GitHub di PokeRogue. Tutti i diritti sugli asset appartengono ai rispettivi creatori originali.',
'Versione del Gioco', 'Data', 'Filtri persistenti',
]